import { GraduationCap, Book, PersonSpeaker, Pencil, Target, Comments, Palette, File, Globe, House } from '@gravity-ui/icons';
import { FaMosque } from 'react-icons/fa';

export const lessons = [
  // English Hub Lessons
  {
    id: 'en-1',
    title: 'Advanced Grammar Fundamentals',
    category: 'English Hub',
    duration: '45 min',
    thumbnail: <GraduationCap />,
    thumbnailUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/M7lc1UVf-VE',
    description: 'Master the core principles of advanced English grammar, including complex sentence structures and advanced tense usage.',
    instructor: 'Robiul Islam',
    difficulty: 'Advanced',
    content: 'In this comprehensive lesson, we dive deep into the nuances of English grammar that separate intermediate learners from fluent speakers. We will cover subjunctive moods, conditional statements, and common pitfalls in academic writing.',
  },
  {
    id: 'en-2',
    title: 'Vocabulary Building Techniques',
    category: 'English Hub',
    duration: '38 min',
    thumbnail: <Book />,
    thumbnailUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/M7lc1UVf-VE',
    description: 'Learn scientific methods to expand your vocabulary quickly and retain new words effectively.',
    instructor: 'Robiul Islam',
    difficulty: 'Intermediate',
    content: 'Expanding your vocabulary isn\'t just about memorizing lists. We explore contextual learning, root word analysis, and mnemonic devices that help you integrate thousands of new words into your daily conversation.',
  },
  {
    id: 'en-3',
    title: 'Spoken English Mastery',
    category: 'English Hub',
    duration: '52 min',
    thumbnail: <PersonSpeaker />,
    thumbnailUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/M7lc1UVf-VE',
    description: 'Improve your pronunciation, fluency, and confidence when speaking English in professional and social settings.',
    instructor: 'Robiul Islam',
    difficulty: 'Intermediate',
    content: 'Confidence is key in communication. This lesson focuses on accent reduction (optional), rhythm, intonation, and strategies to overcome the fear of making mistakes while speaking.',
  },
  {
    id: 'en-4',
    title: 'Writing Skills Excellence',
    category: 'English Hub',
    duration: '41 min',
    thumbnail: <Pencil />,
    thumbnailUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?q=80&w=1073&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    videoUrl: 'https://www.youtube.com/embed/M7lc1UVf-VE',
    description: 'Develop the skills to write clear, persuasive, and professional essays and reports.',
    instructor: 'Robiul Islam',
    difficulty: 'Advanced',
    content: 'From formal emails to academic essays, learn how to structure your thoughts, use transitions effectively, and maintain a consistent tone throughout your writing.',
  },
  {
    id: 'en-5',
    title: 'IELTS Preparation Tips',
    category: 'English Hub',
    duration: '55 min',
    thumbnail: <Target />,
    thumbnailUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/M7lc1UVf-VE',
    description: 'Proven strategies to excel in all four modules of the IELTS exam.',
    instructor: 'Robiul Islam',
    difficulty: 'Intermediate',
    content: 'A complete walkthrough of the IELTS test format, with specific techniques for Reading, Writing, Listening, and Speaking modules to help you reach a Band 8+ score.',
  },
  {
    id: 'en-6',
    title: 'Conversation Practice',
    category: 'English Hub',
    duration: '36 min',
    thumbnail: <Comments />,
    thumbnailUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/M7lc1UVf-VE',
    description: 'Engage in real-world scenarios and dialogue practice to enhance your communicative competence.',
    instructor: 'Robiul Islam',
    difficulty: 'Beginner',
    content: 'Perfect for those starting their journey. We practice everyday scenarios like ordering food, asking for directions, and making small talk in a safe, supportive environment.',
  },

  // IHC Chronicles Lessons
  {
    id: 'ihc-1',
    title: 'Islamic Golden Age History',
    category: 'IHC Chronicles',
    duration: '48 min',
    thumbnail: <Book />,
    thumbnailUrl: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/M7lc1UVf-VE',
    description: 'Explore the scientific, cultural, and economic flourishing in the history of Islam.',
    instructor: 'Robiul Islam',
    difficulty: 'Intermediate',
    content: 'From the 8th to the 14th century, the Islamic world was a global hub of knowledge. We study the House of Wisdom in Baghdad and the contributions of giants like Al-Khwarizmi and Ibn Sina.',
  },
  {
    id: 'ihc-2',
    title: 'Prophet Muhammad & His Legacy',
    category: 'IHC Chronicles',
    duration: '50 min',
    thumbnail: <FaMosque />,
    thumbnailUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/M7lc1UVf-VE',
    description: 'A deep dive into the life, teachings, and the enduring legacy of the Prophet Muhammad (PBUH).',
    instructor: 'Robiul Islam',
    difficulty: 'Intermediate',
    content: 'Understand the historical context of 7th-century Arabia and the transformative impact of the Prophet\'s message on society, ethics, and global history.',
  },
  {
    id: 'ihc-3',
    title: 'Ottoman Empire Chronicles',
    category: 'IHC Chronicles',
    duration: '52 min',
    thumbnail: <House />,
    thumbnailUrl: 'https://images.unsplash.com/photo-1564121211835-e88c852648ab?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/M7lc1UVf-VE',
    description: 'The rise, zenith, and fall of one of the most powerful empires in history.',
    instructor: 'Robiul Islam',
    difficulty: 'Advanced',
    content: 'We trace the journey of the Ottomans from a small principality to a transcontinental empire, exploring their unique administrative systems and cultural achievements.',
  },
  {
    id: 'ihc-4',
    title: 'Islamic Art & Architecture',
    category: 'IHC Chronicles',
    duration: '44 min',
    thumbnail: <Palette />,
    thumbnailUrl: 'https://images.unsplash.com/photo-1542382156909-9ae37b3f56fd?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/M7lc1UVf-VE',
    description: 'Discover the beauty and symbolism behind Islamic geometric patterns, calligraphy, and mosque designs.',
    instructor: 'Robiul Islam',
    difficulty: 'Intermediate',
    content: 'Visualizing spirituality. This lesson examines the philosophy of art in Islam and takes a virtual tour of masterpieces like the Alhambra and the Blue Mosque.',
  },
  {
    id: 'ihc-5',
    title: 'Quranic Insights & Wisdom',
    category: 'IHC Chronicles',
    duration: '46 min',
    thumbnail: <File />,
    thumbnailUrl: 'https://images.unsplash.com/photo-1604933762023-7213af7ff7a7?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/M7lc1UVf-VE',
    description: 'Linguistic miracles and philosophical depths of the Quran.',
    instructor: 'Robiul Islam',
    difficulty: 'Advanced',
    content: 'Exploring the Quran from a literary and philosophical perspective, focusing on its timeless wisdom and relevance to modern ethical dilemmas.',
  },
  {
    id: 'ihc-6',
    title: 'Modern Islamic Movements',
    category: 'IHC Chronicles',
    duration: '40 min',
    thumbnail: <Globe />,
    thumbnailUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/M7lc1UVf-VE',
    description: 'An analysis of contemporary Islamic thought and movements in the 20th and 21th centuries.',
    instructor: 'Robiul Islam',
    difficulty: 'Advanced',
    content: 'How the Islamic world has responded to modernity, colonialism, and globalization. We look at various reformist and traditionalist movements across the globe.',
  },
];
